### ISSUE TITLE
there is clerical error in https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [hugegraph/hugegraph-doc#17]
![image](https://user-images.githubusercontent.com/39079736/52759715-e25bf780-3047-11e9-87e2-78c0cf4c22f9.png)

**Comment by Linary** [comment]
@oushu1zhangxiangxuan1 Thanks for your feedback, we have fixed this error in pr: https://github.com/hugegraph/hugegraph-doc/pull/16
