### ISSUE TITLE
gremlin api 文档 有误

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph-doc#51]
[gremlin api 文档](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/gremlin.html)中异步执行的 Response Status 应该是201
原文如下：

> 7.1.3 向HugeGraphServer发送gremlin语句（POST），异步执行
Method & Url
POST http://localhost:8080/graphs/hugegraph/jobs/gremlin
查询顶点
>
>Request Body
>{
    "gremlin": "g.V('1:marko')",
    "bindings": {},
    "language": "gremlin-groovy",
    "aliases": {}
}
>注意：
>
> >异步执行Gremlin语句暂不支持aliases，可以使用 graph 代表要操作的图，也可以直接使用图的名字， 例如 hugegraph; 另外g代表 traversal，等价于 graph.traversal() 或者 hugegraph.traversal()
>
> Response Status
> 200

**Comment by javeme** [comment]
@chencjiajy 谢谢反馈，也非常欢迎贡献修改。
