### ISSUE TITLE
支持Mac吗？

### ISSUE THREAD

**Issue by Pysamlam** [hugegraph/hugegraph-doc#73]
请问下hugegraph支持Mac安装使用吗

**Comment by javeme** [comment]
支持的

**Comment by Pysamlam** [comment]
怎么安装呢 在官方文档看到的貌似都是window的

发自我的iPhone

**Comment by imbajin** [comment]
官方文档默认就是支持 *nix 环境的, 直接 `bin/` 目录下启动就行, 有啥问题可以随时反馈
